import axios from "axios";
import Head from "next/head";
import React from "react";
import About from "../components/About";
import Contact from "../components/Contact";
import Main from "../components/Main";

import Projects, { Project } from "../components/Projects";
import Skills from "../components/Skills";

// import {
//     useQuery,
//     useMutation,
//     // useQueryClient,
//     QueryClient,
//     // QueryClientProvider,
// } from 'react-query'
// const queryClient = new QueryClient()


const fetchProjects = async () => {
  return axios
    .get("http://localhost:3000/api/projects/")
    .then((res) => res.data);
};
const fetchSkills = async () => {
  return axios
    .get("http://localhost:3000/api/projects/")
    .then((res) => res.data);
};

export async function getStaticProps() {
  
  const pro = await fetchProjects()

  console.log("api data==", pro)
  const projects=pro.projects
  const skills = await fetchSkills()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      projects, skills
    },
  }
}
interface pageProps{
  projects:Project[]
}

export default function Home({projects}:pageProps) {
  return (
    <div>
        {/*<QueryClientProvider client={queryClient}>*/}
      <Head>
        <title>Biruk | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
      <About />
      <Skills />
      <Projects projects={projects}/>
      <Contact />
        {/*</QueryClientProvider>*/}
    </div>
  );
}
